// Stage T — TransformDesigner: full redesign, structure AND style.
//
// Each HTML file is redesigned in TWO client-driven calls (each a separate HTTP
// request with its own 150s budget), which is what keeps a bold, large rewrite
// inside the time limit:
//   phase "structure" — rewrite the <body> markup into a new composition
//                       (new hero, re-laid sections, reordered blocks), while
//                       preserving every class/id/data-attr/handler, all real
//                       content + facts, and the JavaScript.
//   phase "css"        — generate a complete new stylesheet + font links for the
//                       NOW-new structure, so the look matches the new markup.
// A .css/.scss file is a single "cssfile" call (whole-file CSS rewrite).
//
// <script> blocks are pulled out before every call and restored byte-for-byte,
// so JavaScript is never seen or regenerated by the model.
//
// Body: { scan_id, part? } — `part` is a 1-indexed task; the response returns
// `parts` (total tasks) and `done`.

import {
  type DetectedSignal,
  parseBundle,
  presentSignals,
  serializeBundle,
} from "../_shared/pipeline.ts";
import { callClaude, cleanApiKey } from "../_shared/anthropic.ts";
import { adminClient, cors, json, requireUser } from "../_shared/http.ts";
import { buildEntry, recordStageUsage } from "../_shared/usage.ts";

const MODEL = "claude-opus-4-8";
const TRANSFORMABLE = /\.(html?|css|scss)$/i;
const isHtmlPath = (p: string) => /\.html?$/i.test(p);

function extractScripts(html: string): { stripped: string; scripts: string[] } {
  const scripts: string[] = [];
  const stripped = html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi, (m) => {
    const token = `<!--__MIHUTZ_SCRIPT_${scripts.length}__-->`;
    scripts.push(m);
    return token;
  });
  return { stripped, scripts };
}

function restoreScripts(html: string, scripts: string[]): string {
  let out = html;
  const used = new Set<number>();
  scripts.forEach((s, i) => {
    const token = `<!--__MIHUTZ_SCRIPT_${i}__-->`;
    if (out.indexOf(token) !== -1) {
      out = out.replace(token, () => s);
      used.add(i);
    }
  });
  const missing = scripts.filter((_, i) => !used.has(i));
  if (missing.length) {
    const inject = "\n" + missing.join("\n") + "\n";
    out = out.indexOf("</body>") !== -1 ? out.replace("</body>", inject + "</body>") : out + inject;
  }
  return out;
}

// head = up to and including <body ...>; inner = body content; tail = </body>…
function splitBody(html: string): { head: string; inner: string; tail: string } | null {
  const m = html.match(/^([\s\S]*?<body\b[^>]*>)([\s\S]*)(<\/body>[\s\S]*)$/i);
  if (!m) return null;
  return { head: m[1], inner: m[2], tail: m[3] };
}

// Swap the site's stylesheet for the new one and load the new fonts.
function applyNewStyles(html: string, css: string, headExtras: string): string {
  const styleTag = `<style>\n${css}\n</style>`;
  let replaced = false;
  let out = html.replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi, () => {
    if (!replaced) {
      replaced = true;
      return styleTag;
    }
    return "";
  });
  if (!replaced) {
    out = out.indexOf("</head>") !== -1 ? out.replace("</head>", styleTag + "\n</head>") : styleTag + out;
  }
  if (headExtras && headExtras.trim()) {
    out = out.indexOf("</head>") !== -1 ? out.replace("</head>", headExtras + "\n</head>") : headExtras + out;
  }
  return out;
}

const STRUCTURE_SYSTEM =
  `You are TransformDesigner, a world-class web designer. You are given the <body> markup of a page (with its <script> blocks replaced by <!--__MIHUTZ_SCRIPT_N__--> placeholders), a profile of the site, and a list of "AI fingerprint" signals. Return a BOLDLY RESTRUCTURED version of that body markup — a new composition that reads like a top studio built it.

RESTRUCTURE AGGRESSIVELY: rebuild the hero, re-lay-out and reorder sections, introduce semantic wrappers and layout containers, group and re-compose blocks. The DOM should end up meaningfully different — that is the point. Do NOT merely re-indent.

<preserve_exactly>
- Every existing class name, id, data-* attribute, name/for, inline event handler (onclick, onsubmit, …), form action, and href/route. Keep them on the elements they belong to; if you move an element, its attributes move with it. You MAY add new wrapper elements and new class names.
- All real content and FACTS: numbers, names, dates, prices, the logo, images. You may improve wording/tone; never invent facts.
- Every <!--__MIHUTZ_SCRIPT_N__--> placeholder, kept where its element lives (a quiz container etc.). Never delete one; never write <script> content.
</preserve_exactly>

REMOVE ALL EMOJI: strip every emoji from the markup — as icons, beside/inside headings, in badges, buttons, or list items. Replace an emoji icon with a real inline SVG icon or nothing. Emoji are the #1 AI fingerprint; the output must contain zero emoji. (This is the one content exception — you still keep all real facts, numbers, names and text.)

Do NOT write CSS or <style> — a separate stylesheet handles ALL styling. Output only new body markup.

Also emit design_direction (one coherent direction for THIS business from the profile: brand_palette, typography heading+body, layout_principle, personality, rationale). If an <approved_design_direction> is given, reuse it verbatim.

Return ONLY valid JSON: { "design_direction": {...}, "body_html": "<the new body inner HTML>" }. No prose.`;

const CSS_SYSTEM =
  `You are TransformDesigner, a world-class web designer. You are given a page's HTML (structure, classes, ids — <script> blocks shown as placeholders) plus the approved design_direction. Return a COMPLETE NEW STYLESHEET (and the font links to load) that makes the site look premium and coherent, targeting the selectors that exist in this HTML.

Return ONLY CSS — never HTML/JS. Change boldly and match the design_direction: real brand color system, real loaded fonts, a modern type scale, generous spacing rhythm, redesigned buttons/cards/nav/hero, backgrounds, borders, shadows, and CSS layout (grid/flex, gap, order, alignment) to finish the composition. Resolve the listed signals through CSS (no Inter-default, no purple gradient, no generic symmetric card rows; avoid the dark+gold cliché and Playfair-as-elegance). RTL: if the content is Hebrew, use logical properties, right-aligned hero, and Hebrew-capable fonts (Heebo, Assistant, Rubik, Frank Ruhl Libre, Noto Sans Hebrew), body weight >= 500, headings >= 700.

Return ONLY valid JSON: { "stylesheet": "<full CSS, no <style> wrapper>", "head_extras": "<font <link> tags>" }. No prose.`;

const DIRECTION_SCHEMA = {
  type: "object",
  additionalProperties: false,
  properties: {
    brand_palette: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: { token: { type: "string" }, hex: { type: "string" }, role: { type: "string" } },
        required: ["token", "hex", "role"],
      },
    },
    typography: {
      type: "object",
      additionalProperties: false,
      properties: { heading: { type: "string" }, body: { type: "string" } },
      required: ["heading", "body"],
    },
    layout_principle: { type: "string" },
    personality: { type: "array", items: { type: "string" } },
    rationale: { type: "string" },
  },
  required: ["brand_palette", "typography", "layout_principle", "personality", "rationale"],
};

const STRUCTURE_SCHEMA = {
  type: "object",
  additionalProperties: false,
  properties: { design_direction: DIRECTION_SCHEMA, body_html: { type: "string" } },
  required: ["body_html"],
};

const CSS_SCHEMA = {
  type: "object",
  additionalProperties: false,
  properties: { stylesheet: { type: "string" }, head_extras: { type: "string" } },
  required: ["stylesheet"],
};

interface Task {
  file: string;
  phase: "structure" | "css" | "cssfile";
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: cors });
  if (req.method !== "POST") return json({ error: "method not allowed" }, 405);

  const admin = adminClient();
  const user = await requireUser(admin, req);
  if (!user) return json({ error: "unauthorized" }, 401);

  let body: { scan_id?: string; part?: number };
  try {
    body = await req.json();
  } catch {
    return json({ error: "invalid body" }, 400);
  }
  const scanId = body.scan_id;
  if (!scanId) return json({ error: "scan_id required" }, 400);
  let part = Number.isInteger(body.part) && (body.part as number) >= 1 ? (body.part as number) : 1;

  const { data: scan, error: scanErr } = await admin
    .from("scans")
    .select("id, user_id, detection, site_profile, design_direction")
    .eq("id", scanId)
    .single();
  if (scanErr || !scan || scan.user_id !== user.id) return json({ error: "scan not found" }, 404);
  if (!scan.detection) return json({ error: "run_detection_first" }, 409);

  try {
    const apiKey = cleanApiKey(Deno.env.get("ANTHROPIC_API_KEY"));

    const bundlePath = `${user.id}/${scanId}/bundle.txt`;
    const editedPath = `${user.id}/${scanId}/edited-bundle.txt`;
    const { data: file, error: dlErr } = await admin.storage.from("scans").download(bundlePath);
    if (dlErr || !file) throw new Error("bundle_not_found");
    const pristine = parseBundle(await file.text());

    const fileList = [...pristine.keys()].filter((p) => TRANSFORMABLE.test(p)).sort();
    if (!fileList.length) return json({ error: "no_transformable_files" }, 409);

    // Two tasks per HTML file (structure, then css); one per stylesheet file.
    const tasks: Task[] = [];
    for (const f of fileList) {
      if (isHtmlPath(f)) {
        tasks.push({ file: f, phase: "structure" });
        tasks.push({ file: f, phase: "css" });
      } else {
        tasks.push({ file: f, phase: "cssfile" });
      }
    }
    const parts = tasks.length;
    if (part > parts) part = parts;
    const task = tasks[part - 1];

    const present = presentSignals(scan.detection as { signals?: DetectedSignal[] });
    const checklist = present.map((s) => `#${s.id} ${s.name}`).join("\n");

    // The current edited-bundle (accumulated across earlier tasks).
    let edited = new Map<string, string>();
    if (part > 1) {
      const { data: prev } = await admin.storage.from("scans").download(editedPath);
      if (prev) edited = parseBundle(await prev.text());
    }

    const priorDirection = scan.design_direction ?? null;
    const startedAt = Date.now();
    let direction: unknown = priorDirection;

    if (task.phase === "structure") {
      // Rewrite the body markup of the file (from the pristine source).
      const source = pristine.get(task.file) ?? "";
      const { stripped, scripts } = extractScripts(source);
      const bodyParts = splitBody(stripped);
      const inner = bodyParts ? bodyParts.inner : stripped;

      const userContent =
        (priorDirection
          ? `<approved_design_direction>\n${JSON.stringify(priorDirection, null, 2)}\n</approved_design_direction>\nReuse it verbatim.\n\n`
          : "") +
        `<site_profile>\n${JSON.stringify(scan.site_profile ?? {}, null, 2)}\n</site_profile>\n\n` +
        `<signals_to_resolve>\n${checklist}\n</signals_to_resolve>\n\n` +
        `<body_markup file="${task.file}">\n${inner}\n</body_markup>\n\n` +
        `Return the restructured body markup as body_html.`;

      const res = await callClaude({
        apiKey, model: MODEL, effort: "medium", maxTokens: 24000, stream: true,
        system: STRUCTURE_SYSTEM, schema: STRUCTURE_SCHEMA, userContent, timeoutMs: 135_000,
      });
      await recordStageUsage(admin, scanId, buildEntry(`transform_structure_${part}`, MODEL, res.usage, Date.now() - startedAt, "medium"));

      const out = (res.json ?? {}) as { design_direction?: unknown; body_html?: string };
      const newInner = out.body_html;
      if (!newInner || typeof newInner !== "string") throw new Error("empty_structure_output");
      if (out.design_direction && !priorDirection) direction = out.design_direction;

      const rebuilt = bodyParts ? bodyParts.head + "\n" + newInner + "\n" + bodyParts.tail : newInner;
      edited.set(task.file, restoreScripts(rebuilt, scripts));
    } else if (task.phase === "css" || task.phase === "cssfile") {
      // Style the current version of the file (post-structure for HTML).
      const current = edited.get(task.file) ?? pristine.get(task.file) ?? "";
      const isHtml = task.phase === "css";
      const { stripped, scripts } = isHtml
        ? extractScripts(current)
        : { stripped: current, scripts: [] as string[] };

      const userContent =
        (direction
          ? `<approved_design_direction>\n${JSON.stringify(direction, null, 2)}\n</approved_design_direction>\n\n`
          : "") +
        `<site_profile>\n${JSON.stringify(scan.site_profile ?? {}, null, 2)}\n</site_profile>\n\n` +
        `<signals_to_resolve>\n${checklist}\n</signals_to_resolve>\n\n` +
        (isHtml
          ? `The HTML below is for CONTEXT (its selectors). Return a new stylesheet + font links that restyle it.\n\n<html path="${task.file}">\n${stripped}\n</html>`
          : `Rewrite this stylesheet completely; put any @import font rules at the very top.\n\n<css path="${task.file}">\n${stripped}\n</css>`);

      const res = await callClaude({
        apiKey, model: MODEL, effort: "high", maxTokens: 16000, stream: true,
        system: CSS_SYSTEM, schema: CSS_SCHEMA, userContent, timeoutMs: 135_000,
      });
      await recordStageUsage(admin, scanId, buildEntry(`transform_css_${part}`, MODEL, res.usage, Date.now() - startedAt, "high"));

      const out = (res.json ?? {}) as { stylesheet?: string; head_extras?: string };
      const css = out.stylesheet;
      if (!css || typeof css !== "string") throw new Error("empty_css_output");

      edited.set(
        task.file,
        isHtml
          ? restoreScripts(applyNewStyles(stripped, css, out.head_extras ?? ""), scripts)
          : css,
      );
    }

    const up = await admin.storage
      .from("scans")
      .upload(editedPath, new Blob([serializeBundle(edited)], { type: "text/plain" }), {
        upsert: true,
        contentType: "text/plain",
      });
    if (up.error) throw new Error(`storage: ${up.error.message}`);

    const done = part >= parts;
    const update: Record<string, unknown> = { pipeline_status: done ? "applied" : "applying" };
    if (part === 1 && direction) update.design_direction = direction;
    if (done) {
      update.change_log = present.map((s) => ({
        signal_id: s.id,
        file: task.file,
        applied: true,
        applied_by: "redesign",
        reason: null,
      }));
    }
    await admin.from("scans").update(update).eq("id", scanId);

    return json({ ok: true, scan_id: scanId, part, parts, done, phase: task.phase, file: task.file, design_direction: direction });
  } catch (e) {
    const message = e instanceof Error ? e.message : String(e);
    await admin.from("scans").update({ error: `transform: ${message}` }).eq("id", scanId);
    return json({ error: message }, 500);
  }
});
